// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3tRUYXAcY3QUqk0R78mNq_kBKTWJPqw',
    appId: '1:530288780124:web:4c940345d8adf372f99799',
    messagingSenderId: '530288780124',
    projectId: 'grand-public-f4fd5',
    authDomain: 'grand-public-f4fd5.firebaseapp.com',
    storageBucket: 'grand-public-f4fd5.firebasestorage.app',
    measurementId: 'G-SZDG93VJKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0cITq_E5O6gS3ebIm6HpQ2BQ7YXgWCZs',
    appId: '1:530288780124:android:b6f11a19718dce2bf99799',
    messagingSenderId: '530288780124',
    projectId: 'grand-public-f4fd5',
    storageBucket: 'grand-public-f4fd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB69eJxyQLTvpZxJmApTckzWEEV55TlWPQ',
    appId: '1:530288780124:ios:e8bb3ab3f29fe9dff99799',
    messagingSenderId: '530288780124',
    projectId: 'grand-public-f4fd5',
    storageBucket: 'grand-public-f4fd5.firebasestorage.app',
    androidClientId: '530288780124-jc2bbce3jtbi3i5l9qo1api0cmvou6fl.apps.googleusercontent.com',
    iosClientId: '530288780124-sohtqd98eq5rsdhvdpfcf5cepo81mjqt.apps.googleusercontent.com',
    iosBundleId: 'com.maxafrica.gpbenin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB69eJxyQLTvpZxJmApTckzWEEV55TlWPQ',
    appId: '1:530288780124:ios:76379b2aa618d2c8f99799',
    messagingSenderId: '530288780124',
    projectId: 'grand-public-f4fd5',
    storageBucket: 'grand-public-f4fd5.firebasestorage.app',
    androidClientId: '530288780124-k52v1m1c8hjt12rk5598ag8bcvfuctir.apps.googleusercontent.com',
    iosClientId: '530288780124-ge0togu9tue53lpgvb95n4fg56t0ooc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.grandPublicV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh3tRUYXAcY3QUqk0R78mNq_kBKTWJPqw',
    appId: '1:530288780124:web:c1e17a842deeeabdf99799',
    messagingSenderId: '530288780124',
    projectId: 'grand-public-f4fd5',
    authDomain: 'grand-public-f4fd5.firebaseapp.com',
    storageBucket: 'grand-public-f4fd5.firebasestorage.app',
    measurementId: 'G-K4HXLY5YVD',
  );
}